set pagesize 0 embed on;
select * from venues;
select * from events;
describe clients;

SELECT * FROM CLIENTS
ORDER BY CLIENTCOMPANYNAME;

DESCRIBE PROMOTERS;

SELECT PROMOTERBUSINESSNAME,PROMOTERPHONENO,CONTACTPERSON
FROM PROMOTERS;

SELECT * FROM CLIENTS
WHERE POSTCODE = 1001;

SELECT * FROM CLIENTS
WHERE POSTCODE != 1001;

SELECT C.CLIENTCOMPANYNAME, E.EVENTNAME 
FROM CLIENTS C, EVENTS E
WHERE C.CLIENTID = E.CLIENTID;

SELECT DISTINCT V.VENUENAME, E.EVENTNAME 
FROM VENUES V, EVENTS E, EVENTVENUES EV
WHERE V.VENUEID = EV.VENUEID AND E.EVENTID = EV.EVENTID;

SELECT DISTINCT V.VENUENAME, E.EVENTNAME 
FROM VENUES V, EVENTS E, EVENTVENUES EV
WHERE V.VENUEID = EV.VENUEID(+) AND E.EVENTID(+) = EV.EVENTID AND TO_CHAR(EV.BOOKINGDATE, 'MON-YYYY') = 'JUN-2009';

SELECT DISTINCT EV.BOOKINGDATE
FROM VENUES V, EVENTS E, EVENTVENUES EV
WHERE V.VENUEID = EV.VENUEID AND E.EVENTID = EV.EVENTID AND TO_CHAR(EV.BOOKINGDATE, 'MON-YYYY') = 'JUL-2009'
AND V.VENUENAME = 'Local Town Community Theatre'
ORDER BY EV.BOOKINGDATE;

SELECT V.VENUENAME
FROM VENUES V
WHERE V.VENUEID NOT IN(
SELECT VENUEID FROM EVENTVENUES);

SELECT DISTINCT E.EVENTNAME
FROM SPONSORS S, EVENTS E, EVENTSPONSORS ES
WHERE S.BUSINESSNAME = 'Gordon''s Greengrocers'
AND ES.BUSINESSID = S.BUSINESSID
AND ES.EVENTID = E.EVENTID;

SELECT AVG(COSTPERDAY) AS "Average Cost per Day"
FROM VENUES
WHERE VENUECAPACITY BETWEEN 100 AND 120;

SELECT VENUENAME, COSTPERDAY
FROM VENUES
WHERE VENUECAPACITY >= 120
AND COSTPERDAY =
	(SELECT MIN(COSTPERDAY)
	FROM VENUES
	WHERE VENUECAPACITY >= 120);

SELECT COUNT(DISTINCT EVENTID) AS "Number of events in July 2009"
FROM EVENTVENUES
	WHERE TO_CHAR(BOOKINGDATE, 'MON-YYYY') = 'JUL-2009';