DROP TABLE Venues CASCADE CONSTRAINTS PURGE;
DROP TABLE Promoters CASCADE CONSTRAINTS PURGE;
DROP TABLE Clients CASCADE CONSTRAINTS PURGE;
DROP TABLE Sponsors CASCADE CONSTRAINTS PURGE;
DROP TABLE HireCompany CASCADE CONSTRAINTS PURGE;
DROP TABLE ServiceCompany CASCADE CONSTRAINTS PURGE;
DROP TABLE Equipments CASCADE CONSTRAINTS PURGE;
DROP TABLE Events CASCADE CONSTRAINTS PURGE;
DROP TABLE Tickets CASCADE CONSTRAINTS PURGE;
DROP TABLE EventSponsors CASCADE CONSTRAINTS PURGE;
DROP TABLE EventServices CASCADE CONSTRAINTS PURGE;
DROP TABLE EventEquipments CASCADE CONSTRAINTS PURGE;
DROP TABLE EventVenues CASCADE CONSTRAINTS PURGE;

DROP TABLE EliteMember CASCADE CONSTRAINTS PURGE;
DROP TABLE CareerSeminar CASCADE CONSTRAINTS PURGE;
DROP TABLE SeminarAttendance CASCADE CONSTRAINTS PURGE;
DROP TABLE Equipment CASCADE CONSTRAINTS PURGE;
DROP TABLE Client CASCADE CONSTRAINTS PURGE;
DROP TABLE IndividualClient CASCADE CONSTRAINTS PURGE;
DROP TABLE CorporateClient CASCADE CONSTRAINTS PURGE;
DROP TABLE Hires CASCADE CONSTRAINTS PURGE;
DROP TABLE TUnion CASCADE CONSTRAINTS PURGE;
DROP TABLE Business CASCADE CONSTRAINTS PURGE;
DROP TABLE Industry CASCADE CONSTRAINTS PURGE;
DROP TABLE FallsInto CASCADE CONSTRAINTS PURGE;
DROP TABLE Suburb CASCADE CONSTRAINTS PURGE;
DROP TABLE SuburbAdjacency CASCADE CONSTRAINTS PURGE;
DROP TABLE Job CASCADE CONSTRAINTS PURGE;
DROP TABLE CasualJob CASCADE CONSTRAINTS PURGE;
DROP TABLE ContractJob CASCADE CONSTRAINTS PURGE;
DROP TABLE Invoice CASCADE CONSTRAINTS PURGE;
DROP TABLE Review CASCADE CONSTRAINTS PURGE;
DROP TABLE Quotes CASCADE CONSTRAINTS PURGE;

CREATE TABLE EliteMember
(EliteMemberID	VARCHAR2(10)	NOT NULL,
PRIMARY KEY (EliteMemberID));

CREATE TABLE CareerSeminar
(SeminarID		VARCHAR2(10)	NOT NULL,
SeminarTitle	VARCHAR2(200)	NOT NULL,
SemDateTime		DATE			NOT NULL,
SeminarVenue	VARCHAR2(200)	NOT NULL,
PRIMARY KEY (SeminarID));

CREATE TABLE SeminarAttendance
(EliteMemberID	VARCHAR2(10)	NOT NULL,
SeminarID		VARCHAR2(10)	NOT NULL,
PRIMARY KEY (EliteMemberID, SeminarID),
FOREIGN KEY (EliteMemberID) REFERENCES EliteMember(EliteMemberID),
FOREIGN KEY (SeminarID) 	REFERENCES CareerSeminar(SeminarID));

CREATE TABLE Equipment
(EquipmentID	VARCHAR2(10)	NOT NULL,
EqName			VARCHAR2(200)	NOT NULL,
EqStatus		VARCHAR2(30)	NOT NULL,
CONSTRAINT chk_status CHECK (EqStatus IN ('rented', 'available', 'overdue')),
MaxRentDurationDays NUMBER(3)	NOT NULL,
InspectionDate	DATE,
isElectrical	CHAR(1)			NOT NULL,
isMechanical	CHAR(1)			NOT NULL,
PRIMARY KEY (EquipmentID));

CREATE TABLE Client
(ClientNo		VARCHAR2(10)	NOT NULL,
ClientName		VARCHAR2(200)	NOT NULL,
ClientAddress	VARCHAR2(200)	NOT NULL,
ClientEmail		VARCHAR2(200)	NOT NULL,
ClientPhone		VARCHAR2(15)	NOT NULL,
PRIMARY KEY (ClientNo));

CREATE TABLE IndividualClient
(ClientNo		VARCHAR2(10)	NOT NULL,
PropertyOwner	CHAR(1)				NOT NULL,
PRIMARY KEY (ClientNo),
FOREIGN KEY (ClientNo) REFERENCES Client(ClientNo));

CREATE TABLE CorporateClient
(ClientNo		VARCHAR2(10)	NOT NULL,
CorporationName	VARCHAR2(200)	NOT NULL,
CorporationAddress	VARCHAR2(200)	NOT NULL,
PRIMARY KEY (ClientNo),
FOREIGN KEY (ClientNo) REFERENCES Client(ClientNo));

CREATE TABLE Hires
(ClientNo		VARCHAR2(10)	NOT NULL,
EquipmentID		VARCHAR2(10)	NOT NULL,
PickUpDate		DATE			NOT NULL,
DropOffDate		DATE			NOT NULL,
PRIMARY KEY (ClientNo, EquipmentID),
FOREIGN KEY (ClientNo) REFERENCES Client(ClientNo),
FOREIGN KEY (EquipmentID) REFERENCES Equipment(EquipmentID));

CREATE TABLE TUnion
(UnionID		VARCHAR2(10)	NOT NULL,
UnionTitle		VARCHAR2(200)	NOT NULL,
UContactName	VARCHAR2(200)	NOT NULL,
UContactNo		VARCHAR2(15)	NOT NULL,
UEmail			VARCHAR2(200)	NOT NULL,
UAddress		VARCHAR2(200)	NOT NULL,
EliteMemberID	VARCHAR2(10),
PRIMARY KEY (UnionID),
FOREIGN KEY (EliteMemberID) REFERENCES EliteMember(EliteMemberID));


CREATE TABLE Business
(ABNNumber		VARCHAR2(20)	NOT NULL,
ContactName		VARCHAR2(200)	NOT NULL,
BusinessName	VARCHAR2(200)	NOT NULL,
ContactNumber	VARCHAR2(15)	NOT NULL,
ContactEmail	VARCHAR2(200)	NOT NULL,
BusinessAddress	VARCHAR2(200)	NOT NULL,
BusinessPostcode CHAR(4)		NOT NULL,
BType			VARCHAR2(200) 	NOT NULL,
CONSTRAINT chk_BType CHECK (BType IN ('Freelancer', 'Corporate')),
EliteMemberID	VARCHAR2(10),
PRIMARY KEY (ABNNumber),
FOREIGN KEY (EliteMemberID) REFERENCES EliteMember(EliteMemberID));

CREATE TABLE Industry
(IndustryID		VARCHAR2(10)	NOT NULL,
UnionID			VARCHAR2(10)	NOT NULL,
IndustryTitle	VARCHAR2(200)	NOT NULL,
PRIMARY KEY (IndustryID),
FOREIGN KEY (UnionID) REFERENCES TUnion(UnionID));

CREATE TABLE FallsInto
(IndustryID		VARCHAR2(10)	NOT NULL,
ABNNumber		VARCHAR2(20)	NOT NULL,
PRIMARY KEY (IndustryID, ABNNumber),
FOREIGN KEY (IndustryID) REFERENCES Industry(IndustryID),
FOREIGN KEY (ABNNumber) REFERENCES Business(ABNNumber));

CREATE TABLE Suburb
(Postcode	CHAR(4)			NOT NULL,
SuburbName	VARCHAR2(200)	NOT NULL,
PRIMARY KEY (Postcode));

CREATE TABLE SuburbAdjacency
(Postcode1	CHAR(4)			NOT NULL,
Postcode2	CHAR(4)			NOT NULL,
PRIMARY KEY (Postcode1, Postcode2),
FOREIGN KEY (Postcode1) REFERENCES Suburb(Postcode),
FOREIGN KEY (Postcode2) REFERENCES Suburb(Postcode));

CREATE TABLE Job
(JobID			VARCHAR2(10) 	NOT NULL,
ABNNumber		VARCHAR2(20)	NOT NULL,
JobDescription	VARCHAR2(200)	NOT NULL,
UrgencyLevel 	VARCHAR2(200)	NOT NULL,
JobAddress		VARCHAR2(200)	NOT NULL,
Postcode		CHAR(4)			NOT NULL,
IndustryID		VARCHAR2(10) 	NOT NULL,
CONSTRAINT chk_UrgencyLevel CHECK (UrgencyLevel IN ('Low', 'Normal', 'Immediate')),
PRIMARY KEY (JobID),
FOREIGN KEY (IndustryID) REFERENCES Industry(IndustryID),
FOREIGN KEY (ABNNumber) REFERENCES Business(ABNNumber),
FOREIGN KEY (Postcode) REFERENCES Suburb(Postcode));

CREATE TABLE CasualJob
(JobID			VARCHAR2(10)	NOT NULL,
IndividualClientID VARCHAR(10)	NOT NULL,
PRIMARY KEY (JobID),
FOREIGN KEY (JobID) REFERENCES Job(JobID),
FOREIGN KEY (IndividualClientID) REFERENCES IndividualClient(ClientNo));

CREATE TABLE ContractJob
(JobID			VARCHAR2(10)	NOT NULL,
CorporateClientID VARCHAR(10)	NOT NULL,
StartDate 			DATE 			NOT NULL,
EndDate			 DATE 			NOT NULL,
PRIMARY KEY (JobID),
FOREIGN KEY (JobID) REFERENCES Job(JobID),
FOREIGN KEY (CorporateClientID) REFERENCES CorporateClient(ClientNo));

CREATE TABLE Invoice
(InvoiceNo		VARCHAR2(200)	NOT NULL,
Amount			NUMBER(10,2)	NOT NULL,
JobID			VARCHAR2(10)	NOT NULL,
PRIMARY KEY (InvoiceNo),
FOREIGN KEY (JobID) REFERENCES Job(JobID));

CREATE TABLE Review
(ReviewID		VARCHAR2(10)	NOT NULL,
ReviewDate		DATE			NOT NULL,
ReviewRating	NUMBER(1)		NOT NULL,
ReviewText		VARCHAR2(400)	NOT NULL,
JobID			VARCHAR2(10)	NOT NULL,
PRIMARY KEY (ReviewID),
FOREIGN KEY (JobID) REFERENCES Job(JobID));

CREATE TABLE Quotes
(JobID			VARCHAR2(10)	NOT NULL,
ABNNumber		VARCHAR2(20)	NOT NULL,
QuoteAmount		NUMBER(10,2)	NOT NULL,
QuoteStatus		VARCHAR2(200)	NOT NULL,
CONSTRAINT chk_QuoteStatus CHECK (QuoteStatus IN ('contacted', 'posted', 'selected')),
PRIMARY KEY (JobID, ABNNumber),
FOREIGN KEY (JobID) REFERENCES Job(JobID),
FOREIGN KEY (ABNNumber) REFERENCES Business(ABNNumber));