Select TO_CHAR(BOOKINGDATE, 'MON') AS "MONTH", (COUNT(DISTINCT EVENTID) / 3) AS "AVG NUMBER OF EVENTS"
FROM EVENTVENUES
GROUP BY TO_CHAR(BOOKINGDATE, 'MON')
ORDER BY TO_CHAR(BOOKINGDATE, 'MON');

SELECT DISTINCT VENUENAME
FROM VENUES V, EVENTVENUES EV
WHERE MONTHS_BETWEEN(TO_DATE('2009-11-21', 'YYYY-MM-DD') , EV.BOOKINGDATE) > 3 AND EV.VENUEID = V.VENUEID;

SELECT TO_CHAR(BOOKINGDATE, 'MON-YYYY')
FROM EVENTVENUES
GROUP BY  TO_CHAR(BOOKINGDATE, 'MON-YYYY')
HAVING COUNT(DISTINCT EVENTID) = (
	SELECT MAX( COUNT(DISTINCT EVENTID))
	FROM EVENTVENUES
	GROUP BY TO_CHAR(BOOKINGDATE, 'MON-YYYY')
);