Select * from Venues;
Select * from Events;

SELECT * FROM CLIENTS
ORDER BY CLIENTCOMPANYNAME;



--Q11
SELECT R1.EVENTID, tCOSTVENUE + NVL(tCOSTEQUIP, 0) + NVL(tCOSTCATSEC, 0) AS "TOTAL COST"
FROM ( 	SELECT EV.EVNTID, SUM(V.COSTPERDAY) AS tCOSTVENUE
		FROM EVENTVENUES EV, VENUES V
		